In [1]:
import numpy
import sklearn
import os

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [2]:
print('The scikit-learn version is {}.'.format(sklearn.__version__))

The scikit-learn version is 0.18.1.


In [3]:
mapping = {
        0: "5 rupees",
        1: "10 rupees",
        2: "20 rupees",
        3: "50 rupees",
        4: "100 rupees",
        5: "500 rupees",
        6: "1000 rupees",
}

In [27]:
training_data_file = numpy.genfromtxt('MergedDataset2500.csv', delimiter=',', filling_values=0.0)

In [28]:
training_data_file.shape

(91, 2501)

In [29]:
X_Train = training_data_file[:, 1:]
Y_Train = training_data_file[:, 0]

X_Train.shape, Y_Train.shape

((91, 2500), (91,))

In [19]:
test_data_file = numpy.genfromtxt('TestingDataset.csv', delimiter=',', filling_values=0.0)
X_Test =  test_data_file[:,1:]
Y_Test =  test_data_file[:,0]
print("X Test", X_Test.shape)
print("Y Test", Y_Test.shape)

X Test (21, 2500)
Y Test (21,)


In [22]:
mlp = MLPClassifier(solver='sgd', alpha=1e-5, activation='logistic', max_iter=1000, learning_rate='adaptive',
                        hidden_layer_sizes=(50,), random_state=1, verbose=False)

mlp.fit(X_Train, Y_Train)

# predicting the output.
predictions = mlp.predict(X_Test)
print(predictions)

for each in predictions:
    print(mapping[each])


# confusion_matrix
print(confusion_matrix(Y_Test,predictions))

print(classification_report(Y_Test,predictions))

[ 0.  0.  0.  1.  1.  1.  2.  2.  2.  3.  3.  3.  4.  4.  4.  4.  5.  5.
  6.  6.  6.]
5 rupees
5 rupees
5 rupees
10 rupees
10 rupees
10 rupees
20 rupees
20 rupees
20 rupees
50 rupees
50 rupees
50 rupees
100 rupees
100 rupees
100 rupees
100 rupees
500 rupees
500 rupees
1000 rupees
1000 rupees
1000 rupees
[[3 0 0 0 0 0 0]
 [0 3 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 3 0 0 0]
 [0 0 0 0 3 0 0]
 [0 0 0 0 1 2 0]
 [0 0 0 0 0 0 3]]
             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00         3
        1.0       1.00      1.00      1.00         3
        2.0       1.00      1.00      1.00         3
        3.0       1.00      1.00      1.00         3
        4.0       0.75      1.00      0.86         3
        5.0       1.00      0.67      0.80         3
        6.0       1.00      1.00      1.00         3

avg / total       0.96      0.95      0.95        21



/home/sgiri/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:563: ConvergenceWarning: Stochastic Optimizer: Maximum iterations reached and the optimization hasn't converged yet.
  % (), ConvergenceWarning)


In [30]:
userUploadData = numpy.genfromtxt('2500for20.csv', delimiter=',', filling_values=0.0)

In [31]:
userUploadData.shape

(2500,)

In [32]:
mlp = MLPClassifier(solver='sgd', alpha=1e-5, activation='logistic', max_iter=1000, learning_rate='adaptive',
                        hidden_layer_sizes=(40,), random_state=1, verbose=False)

fit = mlp.fit(X_Train, Y_Train)

/home/sgiri/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:563: ConvergenceWarning: Stochastic Optimizer: Maximum iterations reached and the optimization hasn't converged yet.
  % (), ConvergenceWarning)


In [33]:
predictions1 = fit.predict_proba(userUploadData)
print(predictions1)

predictions2 = fit.predict(userUploadData)
for each in predictions2:
    print(mapping[each])

[[ 0.12887848  0.14581889  0.17740063  0.15873874  0.149435    0.12043616
   0.1192921 ]]
20 rupees


/home/sgiri/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/home/sgiri/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
